language: r
r:
  - release

before_install:
  - sudo apt-get install r-cran-tkrplot bwidget
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - devtools
  - roxygen2
  - knitr
  - rmarkdown

cache: packages
warnings_are_errors: false
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual