language: r
r:
  - release

before_install:
  - sudo apt-get install r-cran-tkrplot bwidget
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - devtools
  - roxygen2
  - knitr
  - rmarkdown

cache: packages
warnings_are_errors: false
r_check_args: "--no-vignettes"
r_build_args: "--as-cran --no-vignettes"
